#include "zb_config.h"

#pragma message "ZB_NEIGHBOR_TABLE_SIZE is " ZB_MACRO_TO_STRING(ZB_NEIGHBOR_TABLE_SIZE)
#pragma message "ZB_NWK_ROUTING_TABLE_SIZE is " ZB_MACRO_TO_STRING(ZB_NWK_ROUTING_TABLE_SIZE)
#pragma message "ZB_IEEE_ADDR_TABLE_SIZE is " ZB_MACRO_TO_STRING(ZB_IEEE_ADDR_TABLE_SIZE)

